common: &common
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *common
  database: <%= ENV['DB_DATABASE'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host:     <%= ENV['DB_HOST'] %>
  port:     <%= ENV['DB_PORT'] %>

test:
  <<: *common
  database: bookmarket_test
