common: &common
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *common
  database: <%= ENV['DB_DATABASE'] || 'bokhyllan_development' %>
  username: <%= ENV['DB_USERNAME'] || ENV['USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host:     <%= ENV['DB_HOST'] %>
  port:     <%= ENV['DB_PORT'] %>

test:
  <<: *common
  database: <%= ENV['DB_TEST_DATABASE'] || 'bokhyllan_test'  %>
  username: <%= ENV['DB_TEST_USERNAME'] || ENV['USER']  %>
  password: <%= ENV['DB_TEST_PASSWORD'] %>
  host:     <%= ENV['DB_TEST_HOST'] %>
  port:     <%= ENV['DB_TEST_PORT'] %>
